

export const productConstants = {
    PRODUCTLIST_REQUEST: "PRODUCTLIST_REQUEST",
    PRODUCTLIST_SUCCESS: "PRODUCTLIST_SUCCESS",
    PRODUCTLIST_FAILURE: "PRODUCTLIST_FAILURE",

    PRODUCTSINGLE_REQUEST: "PRODUCTSINGLE_REQUEST",
    PRODUCTSINGLE_SUCCESS: "PRODUCTSINGLE_SUCCESS",
    PRODUCTSINGLE_FAILURE: "PRODUCTSINGLE_FAILURE",

    CATEGORYALL_REQUEST: "CATEGORYALL_REQUEST",
    CATEGORYALL_SUCCESS: "CATEGORYALL_SUCCESS",
    CATEGORYALL_FAILURE: "CATEGORYALL_FAILURE",


}